# Generated by Django 3.2.9 on 2021-11-18 01:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('adult', models.BooleanField()),
                ('backdrop_path', models.TextField()),
                ('genre_ids', models.TextField()),
                ('tmdb_id', models.IntegerField()),
                ('original_language', models.CharField(max_length=50)),
                ('original_title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('popularity', models.FloatField()),
                ('poster_path', models.TextField()),
                ('release_date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('video', models.BooleanField()),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('my_users', models.ManyToManyField(related_name='my_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
